[package]
name = "medusa-capabilities"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
hex.workspace = true
medusa-browser-client = { path = "../medusa-browser-client" }
medusa-config = { path = "../medusa-config" }
medusa-core.workspace = true
medusa-extensions = { path = "../medusa-extensions" }
medusa-github = { path = "../medusa-github" }
medusa-improvement = { path = "../medusa-improvement" }
medusa-provider = { path = "../medusa-provider" }
medusa-transaction-coordinator = { path = "../medusa-transaction-coordinator" }
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
